name: Test exercises

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test exercises
        run: |
          set -e
          for dir in $(find . -type d); do
            cd "$dir"
            echo "Running test for $dir"
            go test -v ./...
          done
